app:
  image:  192.168.57.29:5000/books-ms-centos
  ports:
    - 8080
  net: books-ms-centos
  environment:
    - SERVICE_NAME=books-ms-centos
    - DB_HOST=books-ms-db

app-blue:
  environment:
    - SERVICE_NAME=books-ms-centos-blue
  extends:
    service: app

app-green:
  environment:
    - SERVICE_NAME=books-ms-centos-green
  extends:
    service: app

db:
  container_name: books-ms-db
  image: 192.168.57.29:5000/mongo
  net: books-ms-centos
  environment:
    - SERVICE_NAME=books-ms-db
