app:
  image:  192.168.57.27:5000/books-ms-centos
  ports:
    - 8080
  links:
    - db:db
  environment:
    - SERVICE_NAME=books-ms
  log_driver: syslog
  log_opt:
    syslog-tag: books-ms

db:
  image: mongo
  log_driver: syslog
  log_opt:
    syslog-tag: books-ms
