version: '2'

services:
  app:
    image: 192.168.57.27:5000/books-ms-centos
    ports:
      - 8080
    environment:
      - SERVICE_NAME=books-ms-centos
      - DB_HOST=books-ms-db

  app-blue:
    environment:
      - SERVICE_NAME=books-ms-centos-blue
    extends:
      service: app
    depends_on:
      - db

  app-green:
    environment:
      - SERVICE_NAME=books-ms-centos-green
    extends:
      service: app
    depends_on:
      - db

  db:
    container_name: books-ms-db
    image: mongo
    environment:
      - SERVICE_NAME=books-ms-db
