base:
  image: 192.168.57.27:5000/books-ms-centos
  ports:
    - 8080
  environment:
    - SERVICE_NAME=books-ms-centos

app:
  extends:
    service: base
  links:
    - db:db

app-blue:
  extends:
    service: base
  environment:
    - SERVICE_NAME=books-ms-centos-blue
  links:
    - db:db

app-green:
  extends:
    service: base
  environment:
    - SERVICE_NAME=books-ms-centos-green
  links:
    - db:db

applocal:
  extends:
    service: base
  links:
    - db:db

db:
  image: 192.168.57.29:5000/mongo
