- name: CentOS package is installed
  yum:
    name: docker-engine
    state: present
  tags: [docker-centos]

- name: python-pip is present
  yum:
    name: python-pip
    state: present
  tags: [docker-centos]

- name: docker-py is present
  pip:
    name: docker-py
    version: 1.6.0
    state: present
  tags: [docker]

- name: CentOS Daemon is reloaded
  command: systemctl daemon-reload
  tags: [docker-centos]

- name: vagrant user is added to the docker group
  user:
    name: vagrant
    group: docker
  register: user_result
  tags: [docker-centos]

- name: CentOS service is running
  service:
    name: docker
    state: running
  tags: [docker-centos]

- name: Docker Compose is present
  get_url:
    url: https://github.com/docker/compose/releases/download/1.7.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
  tags: [docker]

- name: Docker Compose permissions are set
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755
  tags: [docker]
